import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gladiatus Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='w-full flex justify-center items-center min-h-screen bg-cover' style={{ backgroundImage: 'url("/bg-image.jpg")' }}>
          <Toaster
            toastOptions={{
              className: '',
              style: {
                background: '#eed7a1'
              }
            }}
          />
          {children}
        </div>
      </body>
    </html>
  )
}
